// P43.1 — DNS-filter resolver config generation (pure). Proves the exact Blocky YAML for a
// given settings object (the live-Blocky proof in the P43.1 bench validates the schema itself),
// plus validation, active-group selection, and the reload-verify probe target.
import test from 'node:test';
import assert from 'node:assert/strict';
import {
  buildBlockyConfig, validateResolverSettings, activeGroups, probeBlockedDomain,
  CATEGORY_META, DEFAULT_SETTINGS,
} from '../dist/dnsfilter.js';

const base = {
  categories: { ads: true, malware: false, adult: false, gambling: false, social: false, streaming: false, gaming: false },
  customBlock: ['blocked.example.com'],
  customAllow: ['allowed.example.com'],
  clientExemptions: ['192.168.88.50'],
  upstreams: ['9.9.9.9', '1.1.1.1'],
  blockType: 'zeroIP',
};

test('buildBlockyConfig — exact YAML (fixture) for ads + custom + exemption', () => {
  const cfg = buildBlockyConfig(base);
  assert.equal(cfg, `# Generated by RubyMIK — do not edit by hand; changes are overwritten on Save & apply.
upstreams:
  groups:
    default:
      - 9.9.9.9
      - 1.1.1.1
ports:
  dns: 53
  http: :4000
blocking:
  blockType: zeroIP
  blockTTL: 1m
  denylists:
    ads:
      - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/light.txt
    custom:
      - |
          blocked.example.com
  allowlists:
    custom:
      - |
          allowed.example.com
  clientGroupsBlock:
    default:
      - ads
      - custom
    "192.168.88.50":
      []
queryLog:
  type: csv
  target: /logs
  logRetentionDays: 1
`);
});

test('activeGroups — respects toggles and skips categories with no lists (gaming)', () => {
  assert.deepEqual(activeGroups(base), ['ads']);
  const all = { ...base, categories: Object.fromEntries(CATEGORY_META.map((c) => [c.key, true])) };
  // gaming ships with no lists → never an active group even when toggled on
  assert.deepEqual(activeGroups(all), ['ads', 'malware', 'adult', 'gambling', 'social', 'streaming']);
  assert.ok(!activeGroups(all).includes('gaming'));
});

test('buildBlockyConfig — clientGroupsBlock.default is [] when nothing is enabled', () => {
  const off = { ...base, categories: { ads: false, malware: false, adult: false, gambling: false, social: false, streaming: false, gaming: false }, customBlock: [] };
  const cfg = buildBlockyConfig(off);
  assert.match(cfg, /clientGroupsBlock:\n {4}default:\n {6}\[\]/);
  assert.ok(!cfg.includes('denylists:\n    ads')); // no ads group emitted
});

test('validateResolverSettings — bad domain / bad IP / missing upstream', () => {
  assert.deepEqual(validateResolverSettings(base), []);
  assert.ok(validateResolverSettings({ ...base, customBlock: ['not a domain'] }).some((e) => /not a valid domain/.test(e)));
  assert.ok(validateResolverSettings({ ...base, clientExemptions: ['999.1.1.1'] }).some((e) => /not a valid IPv4/.test(e)));
  assert.ok(validateResolverSettings({ ...base, upstreams: [] }).some((e) => /at least one upstream/i.test(e)));
});

test('probeBlockedDomain — custom wins, else ads, else null', () => {
  assert.equal(probeBlockedDomain(base), 'blocked.example.com');
  assert.equal(probeBlockedDomain({ ...base, customBlock: [] }), 'google-analytics.com');
  assert.equal(probeBlockedDomain({ ...base, customBlock: [], categories: { ...base.categories, ads: false } }), null);
});

test('DEFAULT_SETTINGS — ads + malware on, sensible upstreams, zeroIP', () => {
  assert.equal(DEFAULT_SETTINGS.categories.ads, true);
  assert.equal(DEFAULT_SETTINGS.categories.malware, true);
  assert.equal(DEFAULT_SETTINGS.blockType, 'zeroIP');
  assert.ok(DEFAULT_SETTINGS.upstreams.length >= 1);
  assert.deepEqual(validateResolverSettings(DEFAULT_SETTINGS), []);
});
